/**
 * Vocabulary Database
 * Contains arrays of objects formatting word, translation, and grammar type.
 * Note: Add matching 'type' entries to ensure the script can pull appropriate distractors.
 */
const vocabularyList = [
    { word: "ausgezeichnet",           translation: "excellent",                   type: "adjective" },
    { word: "die Entscheidung",        translation: "the decision",                type: "noun" },
    { word: "beobachten",              translation: "to observe",                  type: "verb" },
    { word: "der Bereich",             translation: "the area / realm",            type: "noun" },
    { word: "verantwortlich",          translation: "responsible",                 type: "adjective" },
    { word: "beeinflussen",            translation: "to influence",                type: "verb" },
    { word: "die Herausforderung",     translation: "the challenge",               type: "noun" },
    { word: "empfehlen",               translation: "to recommend",                type: "verb" },
    { word: "der Unterschied",         translation: "the difference",              type: "noun" },
    { word: "alltäglich",              translation: "commonplace / daily",         type: "adjective" },
    { word: "vermeiden",               translation: "to avoid",                    type: "verb" },
    { word: "die Unterstützung",       translation: "the support",                 type: "noun" },
    { word: "wichtig",                 translation: "important",                   type: "adjective" },
    { word: "schnell",                 translation: "fast",                        type: "adjective" },
    { word: "die Pflegedokumentation", translation: "the care documentation",      type: "noun" },
    { word: "die Dienstübergabe",      translation: "the shift handover",          type: "noun" },
    { word: "die Patientenverfügung",  translation: "the living will",             type: "noun" },
    { word: "die Wundversorgung",      translation: "the wound care",              type: "noun" },
    { word: "der Flüssigkeitsmangel",  translation: "the dehydration",             type: "noun" },
    { word: "die Nebenwirkung",        translation: "the side effect",             type: "noun" },
    { word: "der Blutzuckerspiegel",   translation: "the blood sugar level",       type: "noun" },
    { word: "die Bettlägerigkeit",     translation: "the bedriddenness",           type: "noun" },
    { word: "die Dekubitusprophylaxe", translation: "the bedsore prevention",      type: "noun" },
    { word: "die Infusion",            translation: "the IV / infusion",           type: "noun" },
    { word: "die Lungenentzündung",    translation: "the pneumonia",               type: "noun" },
    { word: "der Sauerstoff",          translation: "the oxygen",                  type: "noun" },
    { word: "die Schweigepflicht",     translation: "the confidentiality",         type: "noun" },
    { word: "die Körperpflege",        translation: "the personal hygiene",        type: "noun" },
    { word: "das Pflegepersonal",      translation: "the nursing staff",           type: "noun" },
    { word: "die Demenz",              translation: "the dementia",                type: "noun" },
    { word: "die Rehabilitation",      translation: "the rehabilitation",          type: "noun" },
    { word: "die Verstopfung",         translation: "the constipation",            type: "noun" },
    { word: "der Kreislauf",           translation: "the circulation",             type: "noun" },
    { word: "die Genesung",            translation: "the recovery",                type: "noun" },
    { word: "verabreichen",            translation: "to administer",               type: "verb" },
    { word: "dokumentieren",           translation: "to document",                 type: "verb" },
    { word: "lagern",                  translation: "to position (a patient)",     type: "verb" },
    { word: "desinfizieren",           translation: "to disinfect",                type: "verb" },
    { word: "lindern",                 translation: "to alleviate / relieve",      type: "verb" },
    { word: "messen",                  translation: "to measure",                  type: "verb" },
    { word: "überwachen",              translation: "to monitor",                  type: "verb" },
    { word: "verbinden",               translation: "to bandage / dress",          type: "verb" },
    { word: "beruhigen",               translation: "to calm / reassure",          type: "verb" },
    { word: "anordnen",                translation: "to prescribe / order",        type: "verb" },
    { word: "aufklären",               translation: "to educate / inform",         type: "verb" },
    { word: "absaugen",                translation: "to suction",                  type: "verb" },
    { word: "beatmen",                 translation: "to ventilate",                type: "verb" },
    { word: "einleiten",               translation: "to initiate / induce",        type: "verb" },
    { word: "mobilisieren",            translation: "to mobilize",                 type: "verb" },
    { word: "reinigen",                translation: "to clean",                    type: "verb" },
    { word: "spritzen",                translation: "to inject",                   type: "verb" },
    { word: "unterstützen",            translation: "to support",                  type: "verb" },
    { word: "verlegen",                translation: "to transfer (a patient)",     type: "verb" },
    { word: "sich erholen",            translation: "to recover",                  type: "verb" },
    { word: "ansprechbar",             translation: "responsive",                  type: "adjective" },
    { word: "bettlägerig",             translation: "bedridden",                   type: "adjective" },
    { word: "chronisch",               translation: "chronic",                     type: "adjective" },
    { word: "akut",                    translation: "acute",                       type: "adjective" },
    { word: "schmerzstillend",         translation: "pain-relieving",              type: "adjective" },
    { word: "dement",                  translation: "demented",                    type: "adjective" },
    { word: "entzündet",               translation: "inflamed",                    type: "adjective" },
    { word: "fieberhaft",              translation: "feverish",                    type: "adjective" },
    { word: "kreislaufstabil",         translation: "circulatory stable",          type: "adjective" },
    { word: "nüchtern",                translation: "fasting / empty stomach",     type: "adjective" },
    { word: "pflegebedürftig",         translation: "in need of care",             type: "adjective" },
    { word: "steril",                  translation: "sterile",                     type: "adjective" },
    { word: "ansteckend",              translation: "contagious",                  type: "adjective" },
    { word: "bewusstlos",              translation: "unconscious",                 type: "adjective" },
    { word: "blass",                   translation: "pale",                        type: "adjective" },
    { word: "geschwollen",             translation: "swollen",                     type: "adjective" },
    { word: "rezeptpflichtig",         translation: "prescription-only",           type: "adjective" },
    { word: "schwindelig",             translation: "dizzy",                       type: "adjective" },
    { word: "verwirrt",                translation: "confused",                    type: "adjective" },
    { word: "wund",                    translation: "sore / chafed",               type: "adjective" }
];
